"""empty message

Revision ID: 4bc2c8fe5de7
Revises: fcc1b54a4bf7
Create Date: 2020-03-31 20:21:33.056072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc2c8fe5de7'
down_revision = 'fcc1b54a4bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('refresh_token', sa.String(length=36), nullable=False))
    op.drop_column('session', 'session_token')
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.add_column('session', sa.Column('session_token', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_column('session', 'refresh_token')
    # ### end Alembic commands ###
